### ISSUE TITLE
Use Ctrl + Space to force options

### ISSUE THREAD

**Issue by leggsimon** [atom-community/autocomplete-paths#105]
As mentioned in https://github.com/atom-community/autocomplete-paths/issues/104 I do like the idea that if you have entered `./` and press `Ctrl + Space` (or some other keybinding) it'll bring up all the options available to you.

This behaviour does happen if you are already above the 'Minimum  Word Length' setting but it might be nice to be able to start off with this behaviour if no characters have been entered already.

**Comment by saschagehlich** [comment]
I'll implement a feature that will only list files in the current directory when typing `./`

**Comment by saschagehlich** [comment]
This landed in 2.4.0
