### ISSUE TITLE
comments in JS , always brings up stuff

### ISSUE THREAD

**Issue by Oblik-Design** [atom-community/autocomplete-paths#106]
Is it possible for it not to give me this window everytime I start a comment line ?

![capture d ecran 2017-01-19 a 11 16 34](https://cloud.githubusercontent.com/assets/9968597/22115024/6b14eb76-de39-11e6-87e7-c2dfa2bdecf2.png)

**Comment by leggsimon** [comment]
Thanks for the issue @Oblik-Design, yes this is kind of annoying. If anyone would like to open a PR to fix, it would be much appreciated

**Comment by Oblik-Design** [comment]
I've removed the package, it was more pain then gain.

**Comment by saschagehlich** [comment]
Fixed with 2.0.1

**Comment by axe-z** [comment]
thanks :) i'll try it .
