### ISSUE TITLE
Does not work, after installation

### ISSUE THREAD

**Issue by wilsonmontelo** [atom-community/autocomplete-paths#107]
After you install the autocomplete path. Do I need to modify an item on Atom? Well, it did not work.

**Comment by leggsimon** [comment]
You shouldn't need to.

**Comment by giolf** [comment]
I confirm, it doesnt work anymore

**Comment by NoreagoCan** [comment]
doesn't seem work anymore

**Comment by leggsimon** [comment]
Do you also have autocomplete-plus installed?

**Comment by NoreagoCan** [comment]
I do indeed. It seems that it was conflicted with another module i had installed but didnt use so i uninstalled it. 
It works now with on the html side completing file paths, but not on the scss side.... any suggestions why that might be?

**Comment by saschagehlich** [comment]
Please check out 2.0.1
