### ISSUE TITLE
how to insttall it ?   Please make sure you have autocomplete-plus installed as well

### ISSUE THREAD

**Issue by jpca999** [atom-community/autocomplete-paths#108]
i did this 

![image](https://cloud.githubusercontent.com/assets/1026325/25450160/0254f988-2a8c-11e7-9e3c-bb2af49f7223.png)

what next ?

**Comment by giolf** [comment]
next uninstall because it doesnt work anymore 🍺

**Comment by jpca999** [comment]
okay , lol so what to use ?

**Comment by giolf** [comment]
It depends: I'm using `autocomplete-modules` to require or import modules. if you're searching something for any file honestly i don't know.
