### ISSUE TITLE
Autocompletion for sass file should not have the underscore prefixe and the extention (.scss or .sass)

### ISSUE THREAD

**Issue by Sliverside** [atom-community/autocomplete-paths#109]
Hi,
thanks for this useful package, there is my logic : 

if path_extension == '.sass' or '.scss' {
- delete first_character
-  delete extension

}
sass/scss files are uniquely imported in sass/scss files so that should do the job.
It's just an idea, I don't know how this package work,
thank you !

**Comment by saschagehlich** [comment]
Version 2.0.1 supports this!
