### ISSUE TITLE
Updating to “autocomplete-paths@2.0.1” failed.

### ISSUE THREAD

**Issue by borishere** [atom-community/autocomplete-paths#113]
![screenshot_3](https://user-images.githubusercontent.com/4622497/29218814-b8661c26-7ebe-11e7-9232-d6b96dee635d.png)

**Comment by saschagehlich** [comment]
Haven't used this on windows yet. I introduced file watchers (using native extensions) with 2.0.0, which probably cause this issue. Will look into this.

**Comment by borishere** [comment]
I`m on Windows 10 64-bit

**Comment by saschagehlich** [comment]
@borishere 2.0.2 upgrades pathwatcher to a newer version, which might fix this issue. Could you check, please? :)

**Comment by ddirks** [comment]
I just ran into the same installation error with 2.0.2, also on Windows 10 64-bit. The error output looks to be substantially identical to that posted above.

**Comment by saschagehlich** [comment]
v2.1.0 now uses atom's pre-built version of `pathwatcher`. Please try again with the new version!

**Comment by saschagehlich** [comment]
Closing this for now. Please re-open if issue persists.
