### ISSUE TITLE
Autocompletion broken for relative paths

### ISSUE THREAD

**Issue by timdp** [atom-community/autocomplete-paths#123]
With version 1.x, if I'm in a JS project inside `src/a.js` and start typing `import b from './b`, it will autocomplete to `'./b.js'`. (I'd love to be able to strip off the `.js` automatically, but anyway.)

With version 2.x, it'll import it as `'././b.js'`. It looks like it's just replacing everything until the last slash that I've typed, rather than the full path that I was typing manually. This of course is aggravated if the path starts with one or more instances of `../`, because then, in addition to the redundancy, it just breaks.

Typing just `import b from 'b` works, in the sense that it auto-enters the relative path, but I think it should also be able to understand me if I'm _telling_ it what the actual path is.

Additionally, I'm not a fan of the way I now get project-relative paths as suggestions rather than file-relative paths. Project-relative ones are longer and therefore harder to read. Is there a toggle?

Sorry to criticize, but so far, version 2 feels like a regression, unfortunately.

**Comment by saschagehlich** [comment]
> With version 2.x, it'll import it as '././b.js'. It looks like it's just replacing everything until the last slash that I've typed, rather than the full path that I was typing manually. This of course is aggravated if the path starts with one or more instances of ../, because then, in addition to the redundancy, it just breaks.

That's correct and it will be fixed in a future release (I'm actually working on it right now)

> Additionally, I'm not a fan of the way I now get project-relative paths as suggestions rather than file-relative paths. Project-relative ones are longer and therefore harder to read. Is there a toggle?

Not sure what you mean - could you provide an example?

**Comment by timdp** [comment]
> That's correct and it will be fixed in a future release (I'm actually working on it right now)

Okay, cool!

> Not sure what you mean - could you provide an example?

It relates to relative paths, I guess. Let's say I have `src/util/camelcase.js` and I'm in `src/index.js`. If I want to import `camelcase`, I'm more interested in `util/`, than I am in `src/`, but it always shows me the full path. I don't think this was the case before.

I was just in a project that goes quite a few levels deep, where I used to use this package a lot for that exact reason. Now, with version 2.3.0, every autocompleted path is very long, so it takes me longer to read it and find the part that I'm really interested in.

**Comment by saschagehlich** [comment]
So your suggestion is:

* If a directory path is entered, e.g. `./util`, it should only (recursively) list files in `src/util`
* If requesting a relative path using `./ [...]` it should strip the current file's directory path from the results

Correct?

**Comment by timdp** [comment]
At the risk of just sounding conservative: I liked the old behavior better, and what you're describing is basically the old behavior, right? :slightly_smiling_face:

**Comment by saschagehlich** [comment]
Basically, yes. With the addition of being able to just enter a random string and it lists all files matching the string (as long as no specific directory path is entered).

**Comment by timdp** [comment]
Yep, that's of course a nice improvement. Thanks!

**Comment by saschagehlich** [comment]
@timdp Could you check out 2.4.0? :)

**Comment by timdp** [comment]
Ooh, you even got the `.js` out. Great work!

**Comment by saschagehlich** [comment]
Yeah that was an essential feature for 2.0.0. Using scopes, you can specify when and how autocomplete-paths should trigger. A scope can include a `replaceOnInsert` option: https://github.com/atom-community/autocomplete-paths/blob/master/lib/config/default-scopes.js#L14
