### ISSUE TITLE
How to exclude /node_modules/ from indexing?

### ISSUE THREAD

**Issue by doctorofscience** [atom-community/autocomplete-paths#124]

**Comment by saschagehlich** [comment]
For projects backed by git, add `node_modules` to your `.gitignore`. For projects not backed by git, theres no option right now

**Comment by saschagehlich** [comment]
You can now add `node_modules` to the `core.ignoredNames` option. `autocomplete-paths` will then ignore on the next indexing.

**Comment by FallingSnow** [comment]
I have `node_modules` in my `.gitignore`. Everything else combined is under 100 files however I still get the 2000 files warning.

Going to downgrade to 1.x.x for now.

**Comment by saschagehlich** [comment]
@FallingSnow Does `node_modules` appear greyed out, like so?

![screenshot 2017-08-15 20 02 33](https://user-images.githubusercontent.com/119684/29329001-b49c7782-81f4-11e7-9579-c5bc9eca375e.png)

**Comment by FallingSnow** [comment]
Yes.

**Comment by saschagehlich** [comment]
Well, then there's something else in your project that's not .gitignored.

**Comment by FallingSnow** [comment]
Ah found it. It was a directory in a project I don't have open. Thx.

Any chance of getting a setting in autocomplete-paths to ignore a list of globs?

**Comment by saschagehlich** [comment]
autocomplete-plus uses atom's `ignoreNames` option, you can use that one

**Comment by daiyi** [comment]
You can add "node_modules" to the list under `Preferences > Core Settings > Ignored Names`

**Comment by sorcamarian** [comment]
This discussion on Atom forum might be helpful: https://discuss.atom.io/t/gitignored-files-are-hidden-from-tree-view-regardless-of-setting/8724/4

**Comment by samkahchiin** [comment]
`ignoredNames` options seems not available in `autocomplete-paths` anymore. (I added it into the `config.cson` file and it disappear after I reload it). 
Trying `ignoredPatterns` but it is only working if I use absolute path ([github link](https://github.com/atom-community/autocomplete-paths/issues/178)) which doesn't really make sense for me.
