### ISSUE TITLE
atom 1.19.0 Problem with use

### ISSUE THREAD

**Issue by linjialiang** [atom-community/autocomplete-paths#126]
If there are too many directories, the atom editor is directly jammed
If the directory is small, it will not be wrong, but it will not automatically complete the full path

**Comment by saschagehlich** [comment]
Please provide more information:

* Which OS are you on?
* Please specify what you mean with "it will not complete the full path". Can you name an example?

**Comment by linjialiang** [comment]
![default](https://user-images.githubusercontent.com/8848263/29247625-35eefff0-803b-11e7-9c9f-d95e9623138e.png)
Sorry, my English is not good enough. I can't express it clearly. Please forgive me！

**Comment by linjialiang** [comment]
win10_x64 OS

**Comment by linjialiang** [comment]
Sorry, my English is not good enough. I can't express it clearly. Please forgive me！
win10_x64 OS
atom 1.19.0
autocomplete-paths 2.4.0

---

The problem I have now is that the path can't be filled in any situation, as if I hadn't installed autocomplete paths

**Comment by saschagehlich** [comment]
Thank you @linjialiang - I'll investigate the Windows issues once I get access to a windows machine

**Comment by saschagehlich** [comment]
For now i'll move the discussion to #118

**Comment by linjialiang** [comment]
Ok, I've got the # 188 problem too, and maybe he hasn't noticed that the path is not complete
