### ISSUE TITLE
Stoped working in html files

### ISSUE THREAD

**Issue by mgibas** [atom-community/autocomplete-paths#131]
Im was using plugin mostly in html files for html imports like:
`<link rel="import" href="../../bower_components/polymer/polymer-element.html">`

**Comment by saschagehlich** [comment]
As you can see in the README, autocomplete-paths does not support HTML by default. You can add the following scope to your config.cson to add support:

```coffeescript
  "autocomplete-paths":
    scopes: [
      {
        scopes: ['text.html.basic'],
        prefixes: [
          'src=[\'"]',
          'href=[\'"]'
        ],
        extensions: ['js', 'png', 'gif', 'jpeg', 'jpg', 'tiff', 'html'],
        relative: true
      }
    ]
```

**Comment by linjialiang** [comment]
I'm sorry!
I don't know the location of this configuration file

**Comment by linjialiang** [comment]
![default](https://user-images.githubusercontent.com/8848263/29303531-1a5550ba-81c0-11e7-8f80-82ee58c3bef6.png)

**Comment by linjialiang** [comment]
![default](https://user-images.githubusercontent.com/8848263/29303585-6eae5c7e-81c0-11e7-8019-fc5c1b2db999.png)

**Comment by linjialiang** [comment]
@saschagehlich 
Thank you very much.
Now it's ready for normal use

**Comment by mgibas** [comment]
Yeah, that works nice except it doesn't resolve paths in `bower_components` folder - any settings for that ? :)

**Comment by saschagehlich** [comment]
@mgibas autocomplete-paths ignores files in .gitignored directories. The `bower_components` directory is either ignored by git or by atom (Atom's `ignoredNames` option)

**Comment by ljpendergrass** [comment]
Don't mean to zombie this thread, but for the less competent like me, **be sure to close out of your "Settings" tab when updating config.cson.** It seems like the "scopes" field in the package settings will try to override the scopes field in the cson, and the two will fight. Add the above HTML scope code to your cson with Settings closed, save the config, and then everything will work properly. Hopefully I save some others some time :)

**Comment by mgibas** [comment]
@saschagehlich yeah, it is ignored by git so it works as intended. Though for web development its pretty crucial thing to be able to import bower_components. Is it possible to override that settings somehow in `autocomplete-paths` ?

**Comment by youngjuning** [comment]
I waste much time to fix this problem.

**Comment by mgibas** [comment]
So I turned off **_Exclude VCS Ignored Paths_** option in Atom and _**Ignored Names**_ in `autocomplete-paths` but my `bower_components` are still ignored due to having them in `.gitignore` - is that how it should works ? Shouldn't that be controlled by atom _**Exclude VCS Ignored Paths**_ option ?

**Comment by linjialiang** [comment]
The author has solved these problems!
Your upgrade version will do

**Comment by saschagehlich** [comment]
@mgibas Right now, autocomplete-paths does not regard the `Exclude VCS Ignored Paths` option. I'll add a ticket for this and work on it as soon as I have some free time

**Comment by mgibas** [comment]
Great, really appreciate that.

**Comment by youngjuning** [comment]
@linjialiang How can I add picture in comment like you? Thanks.

**Comment by youngjuning** [comment]
![](https://user-images.githubusercontent.com/8848263/29303585-6eae5c7e-81c0-11e7-8019-fc5c1b2db999.png)

**Comment by photonauta35** [comment]
I'm trying to add file path images into markdown files. 

I follow this issue and I put this into config.cson, but is not working. Maybe the problem could be the prefixes, right? Images, into .md files are included like that: 

```
![My image name](images/css_03_css_selectors.png)
```

So, I tryed:

```
  "autocomplete-paths":
    scopes: [
      {
        scopes: ['source.md'],
        prefixes: [
          '\\]\\(["]'
        ],
        extensions: ['jpg', 'jpeg', 'svg', 'png'],
        relative: true,
        includeCurrentDirectory: true,
        projectRelativePath: false
      }
    ]
```

**Comment by joeljpa** [comment]
Another "Don't mean to zombie this thread, but for the less competent like me (@ljpendergrass)".
At the time of writing, enabling html support is only a matter of enabling it in the package settings "Enable Html Support". I spent a good 15 min doing what the thread said (didn't work for me) only to realise this.

**Comment by Samuel91** [comment]
How can I enable HTML support even for .php files?

**Comment by aminya** [comment]
> How can I enable HTML support even for .php files?

@Samuel91 You need to add the extensions and their prefix here. I will be happy to accept a PR
