### ISSUE TITLE
I haven't been able to use it since 1.19.0

### ISSUE THREAD

**Issue by linjialiang** [atom-community/autocomplete-paths#134]
Now the plugin has been upgraded to 2.6.0 but I still can't use it, it's not working！
After installing the plug-in, I didn't configure it.
Does this plug-in installation require special configuration?

**Comment by linjialiang** [comment]
在安装了插件之后，我没有进行配置。
这个插件安装需要特殊配置吗?

**Comment by saschagehlich** [comment]
Please specify `it's not working`

**Comment by linjialiang** [comment]
Atom did not give me any description of the error
The only problem is that the path cannot be filled！

**Comment by saschagehlich** [comment]
What OS are you on? Could you show me an example of what's not working? `autocomplete-paths` only triggers when really needed.

**Comment by linjialiang** [comment]
![default](https://user-images.githubusercontent.com/8848263/29303143-1a45a17c-81bd-11e7-84b9-5762c2da1d75.png)

**Comment by saschagehlich** [comment]
Duplicate of #131

**Comment by linjialiang** [comment]
@saschagehlich 
I'm sorry!
I don't know the location of this configuration file
