### ISSUE TITLE
use problem

### ISSUE THREAD

**Issue by Gavery** [atom-community/autocomplete-paths#135]
this package does not work for my edit tool !it is does not work,however,the others are working well for me,my operating system is window 7.please give me some suggestions.

**Comment by BlaM** [comment]
There is no way anybody can help you if you don't say what is going wrong.

**Comment by saschagehlich** [comment]
I really need to set up an issue template.

**Comment by BlaM** [comment]
In theory I would expect that programmers understand the concept of bug reports...

**Comment by saschagehlich** [comment]
Since you didn't provide additional information in 2 days, I'm closing this issue.
