### ISSUE TITLE
Unable to save scope example from the docs

### ISSUE THREAD

**Issue by westmark** [atom-community/autocomplete-paths#136]
Hi! I basically copy-pasted the scopes example in the docs, but Atom refuses to validate the change. This is what config.cson looks like before I hit save

```
"autocomplete-paths": {
    scopes: [
      {
        scopes: ['source.js'],
        prefixes: [
          'import\\s+.*?from\\s+[\'"]',
          'require\\([\'"]',
          'define\\(\\[?[\'"]'
        ],
        extensions: ['js', 'jsx', 'ts', 'coffee'],
        relative: true,
        includeCurrentDirectory: true,
        replaceOnInsert: [
          ['.jsx?$', ''],
          ['.ts$', ''],
          ['.coffee$', '']
        ]
      },
    ]
  }
```
Now, I'm no Atom plugin expert, but it seems to me that there is a bug on this line

https://github.com/atom-community/autocomplete-paths/blob/master/lib/config/index.js#L31

Shouldn't `type` be `array` rather than `['array']`? If so the definitions below have the same bug.

**Comment by saschagehlich** [comment]
Hey @westmark,

which version of Atom are you on? I'm on 1.19 and it works like a charm this way.

**Comment by westmark** [comment]
I'm on 1.19.1 and autocomplete-paths@2.8.0

**Comment by westmark** [comment]
Wow, just tried again (copied the text from my comment above) and now it works. No idea why. Guess there must have been som invisible space or something in the original which got removed when I pasted it here. Sorry for the trouble.
