### ISSUE TITLE
how to use ignored names to shield node_modules in node.js project?

### ISSUE THREAD

**Issue by canxer314** [atom-community/autocomplete-paths#137]
everytime I start atom, autocomplete-paths package takes a long time building path cache and then crash for the huge number of files in node_modules folder, I want to know hwo to shied node_modules through ignored names option.

**Comment by saschagehlich** [comment]
Go to Preferences -> Core and scroll down to "Ignored Names". Add `node_modules` to that list.

**Comment by canxer314** [comment]
thanks
