### ISSUE TITLE
autocomplete-paths is not working after new updates

### ISSUE THREAD

**Issue by SachinKodagoda** [atom-community/autocomplete-paths#140]
I am using windows 10 new version
atom also new version
recently i saw a update and i made the update.. after that autocomplete-paths is not working properly. it doesn't complete paths in HTML. it works fine with css but not html

**Comment by SachinKodagoda** [comment]
and some paths css giving is wrong..

**Comment by YogiOneKanobi** [comment]
Having the same issues. Was really enjoying this package as it is supremely useful. Now that its not working I realize how much I relied on it.

Seems like there are 0 lookups executing at all.

**Comment by mgibas** [comment]
take a look here #131

**Comment by FlatlineTV** [comment]
@mgibas thanks, worked out for me!

Also, make sure to read upon what @ljpendergrass said down in the comments.

**Comment by FlatlineTV** [comment]
Actually, when using via .scss files, doesnt seem to show any of the folders/files I have: 
![image](https://user-images.githubusercontent.com/13840075/29644774-ce5eef30-882d-11e7-8389-f9961970ff73.png)

**Comment by petrchutny** [comment]
Same problem here @FlatlineTV. Did you find any ways to fix this?

**Comment by levianlp** [comment]
i have the same issues did you guys find the solution for it?

**Comment by FlatlineTV** [comment]
> i have the same issues did you guys find the solution for it?

I believe I stuck to version 1.46.0 and never ever updated since then.

**Comment by aminya** [comment]
Could you open a new issue? This was fixed in 2017.

**Comment by levianlp** [comment]
@aminya already open a new issue sorry for that
