### ISSUE TITLE
File extensions not included

### ISSUE THREAD

**Issue by Stardog** [atom-community/autocomplete-paths#141]
I believe a recent update prevented file extensions from autocomplete inclusion. Since 2.7.0, I can still select files but the .js and .jsx extensions are not added after pressing enter or tab.

I see there is an option to suppress extension on completion but I have not tinkered with the config file.

Atom 1.9.8
autocomplete-paths 2.8.0

**Comment by saschagehlich** [comment]
That's a feature of 2.0.0 and is intended

**Comment by Stardog** [comment]
No problem. I'll change my webpack. Thank you.
