### ISSUE TITLE
Compatibility with `project-viewer` package

### ISSUE THREAD

**Issue by rainjm** [atom-community/autocomplete-paths#146]
Sometimes appearing.

Under the project，Open the settings.
Use [project-viewer](https://atom.io/packages/project-viewer) to switch the project.

Not 100% repeated emergence.

Seems to have a relationship with the window switch。

**Comment by saschagehlich** [comment]
Of course it's appearing, because it needs to rebuild the paths cache when switching projects.

**Comment by rainjm** [comment]
But sometimes for a long time did not respond

**Comment by rainjm** [comment]
@saschagehlich 
In the 'rebuild path cache ...', use [project-viewer](https://atom.io/packages/project-viewer) to switch the other project, then return. 'Rebuilding paths Cache ...' disappear.

**Comment by rainjm** [comment]
Just now, I'll reproduce again. The PC is frozen!

**Comment by saschagehlich** [comment]
What OS are you on?

**Comment by rainjm** [comment]
@saschagehlich macOS

**Comment by rainjm** [comment]
![image](https://user-images.githubusercontent.com/9592236/30156416-309e3938-93f2-11e7-9562-9715211b8d28.png)

Use project-viewer this function. Very large probability of frozen.

**Comment by saschagehlich** [comment]
Should be fixed with 2.12.0

**Comment by rainjm** [comment]
Cool, now normal, thanks
