### ISSUE TITLE
Regard `Exclude VCS Ignored Paths` core option

### ISSUE THREAD

**Issue by saschagehlich** [atom-community/autocomplete-paths#149]

**Comment by love8587** [comment]
I really really would like to get this features!!

**Comment by saschagehlich** [comment]
Released with 2.11.0

**Comment by love8587** [comment]
<img width="430" alt="screen shot 2017-09-03 at 7 57 28 pm" src="https://user-images.githubusercontent.com/3261890/30002350-3e1bd8bc-90e2-11e7-8dd2-2fecf81ce44c.png">

I can't find out how to set `core.ignoredNames` configuration. So I looked some code to see how to run it. So I tried to set the configuration to except some path I don't want. And Is it correct!?

**Comment by saschagehlich** [comment]
@love8587 In the preferences view, you can specify the `ignoredNames` option:

![screen shot 2017-09-03 at 1 29 15 pm](https://user-images.githubusercontent.com/119684/30002544-f1e847c2-90ab-11e7-8869-a7b55a532a52.png)

What do you mean with ` support the rules`?

**Comment by love8587** [comment]
@saschagehlich Oh, That's what I want. I didn't know there is already the option in the CORE tab. I only found out in the Package setting tab. Sorry to confuse you, It's okay now! Thanks! :)
