### ISSUE TITLE
How can I use relative configuration?

### ISSUE THREAD

**Issue by love8587** [atom-community/autocomplete-paths#152]
I set a flag of relative path like here:
<img width="258" alt="screen shot 2017-09-05 at 6 34 50 pm" src="https://user-images.githubusercontent.com/3261890/30054990-f1d32f2c-9268-11e7-820e-a2066b391d21.png">

Step 1, After reloading I tried put path on as an absolute path with the module.
<img width="570" alt="screen shot 2017-09-05 at 6 32 40 pm" src="https://user-images.githubusercontent.com/3261890/30054953-d3a79f2e-9268-11e7-9fe3-3589145c1baf.png">

Step 2, But the path was put on as a relative. 
<img width="305" alt="screen shot 2017-09-05 at 6 32 49 pm" src="https://user-images.githubusercontent.com/3261890/30054957-d5db0380-9268-11e7-9469-2bda180ab3c5.png">

* I'm using an NPM module to find local module 
`require('app-module-path').addPath(__dirname)`

**Comment by saschagehlich** [comment]
The relative option is per-scope. So you'll need to override the scope and set its `relative` property to `false`.
