### ISSUE TITLE
Add option to disable version 2 caching mechanism?

### ISSUE THREAD

**Issue by ddirks** [atom-community/autocomplete-paths#157]
With the advent of version 2.x of autocomplete-paths, the package has become unusable for me. This is because I do a large portion of my work in a Very Large Project (100,000+ total files) (not git-based). Obviously the default 2000 file limit imposed by autocomplete-paths is out, and (as expected) setting the maxFileCount to a sufficiently large number causes the path caching step to take an unworkably long time.

My solution has been to revert to autocomplete-paths version 1.0.5. This works with the Very Large Project, but also means I can't take advantage of the other cool things in version 2+, like the "replaceOnInsert" feature, which would be quite useful to me.

I understand that version 2 is a complete rewrite of version 1, so just plopping the old non-caching (I assume?) code back in is not an option. My question is: would it be possible in the version 2 codebase to optionally disable the caching and mimic the behavior of version 1? The non-cached version would be slower than the cached version, of course, but having the suggestions come up after a wait is far more useful than not having them at all.

If such a thing were possible, I would have two suggestions for the user interface:

1. Switch to the non-cached behavior automatically if the number of files indexed exceeds maxFileCount, rather than having a single on/off switch. That way I could have the speedy cached behavior for smaller projects, but also have path autocompletion for large projects.
2. Allow the user to choose whether paths are autocompleted automatically or only when requested (via ctrl-space, say). With caching off, the "on request" mode seems more friendly to me, but others may have other ideas.

Thanks for your consideration, and for all your efforts on the autocomplete-paths functionality.

**Comment by saschagehlich** [comment]
Yep, that's definitely on the list! I'll work on it as soon as I find some spare time

**Comment by tagrudev** [comment]
@saschagehlich I have the same problem with a large project, is this something you plan on including soon ?

**Comment by alflanagan** [comment]
Would it be possible to reduce the priority (or i/o priority) of the process that does the caching? As-is, when I open atom in my home directory, other programs are slowed or stopped as well.
