### ISSUE TITLE
Autocomplete paths for .pug

### ISSUE THREAD

**Issue by ChillOut05** [atom-community/autocomplete-paths#159]
I just can't understand how to add custom scope to config.cson properly. I had read other similar issues like custom **.vue** scope setup and for **basic html** files, also looked into **default-scopes.js** for an answer but it seems that I can't see the pattern of writing custom scope. In my example popup with list of files need to be trigger after I press space after **include**: 
```javascript
"autocomplete-paths":
    scopes: [
      {
        scopes: ['text.html.pug'],
        prefixes: [
          'include=[ ]'
        ],
        extensions: ['pug'],
        relative: true
      }
    ]
```
Also here I don't know should I write **scopes: ['_text.html.pug_']** or **scopes: ['_source.pug_']**. But however both options doesn't work.

Atom 1.20.0
autocomplete-paths 2.11.0

**Comment by saschagehlich** [comment]
The `prefixes` option takes an array of regular expressions that need to be found *before* the cursor in order for the autocompletion to trigger. In your example, that would be something like `['include\s+']`

The correct scope identifier can be found by opening a pug file and using the `Editor: Log Cursor Scope` command.
