### ISSUE TITLE
No .svg support?

### ISSUE THREAD

**Issue by FlatlineTV** [atom-community/autocomplete-paths#162]
![eiwlvod](https://user-images.githubusercontent.com/13840075/30478252-3344efe6-99c5-11e7-9a67-4dfd9a2223f3.gif)

**Comment by philerck** [comment]
In lib/config/option-scopes.js I add to extensions:  , 'webp', 'svg' an I got svg and webp support.
Maybe not the best solution but works.

**Comment by FlatlineTV** [comment]
@philerck I appreciate the hot fix my dude! I ended up uninstalling the package overall. Too many issues, was extremely beast before.
