### ISSUE TITLE
"Rebuilding paths cache..." and Atom is frozen when I start it (Ubuntu 16.04)

### ISSUE THREAD

**Issue by EdwardDiehl** [atom-community/autocomplete-paths#166]
### Description
Atom is frozen when I start it. The system becomes unresponsive (Ubuntu 16.04)

### Versions

```
$ atom -v
Atom    : 1.20.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

```
autocomplete-paths@2.11.0
```

```
$ apm -v
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.7.4
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

```
$ uname -mrs
Linux 4.4.0-96-generic x86_64
```

**Comment by saschagehlich** [comment]
Please try again with atom 1.12.0. Please reopen issue if it persists.

**Comment by EdwardDiehl** [comment]
I updated the addon to 2.12.0. Looks like the issue is fixed, it opens new projects very fast! I didn't mention in my first message that it was happening only when you open some project for first time with the previous version of the plugin.
Thanks @saschagehlich

**Comment by ricardograca** [comment]
I'm having this issue with version 2.12.2. I think it only happens when opening a project that hasn't been opened in a long time. This isn't easy to debug since the system becomes almost completely unresponsive. Mouse movement alone takes several seconds to show up.

**Comment by dmig** [comment]
Same for me: had this problem with autocomplete-paths 2.12.1, faced it again with 2.12.2

**Comment by stdavis** [comment]
I'm having this same issue with 2.12.2. Everything I open atom I see the "rebuilding paths cache..." message in the status bar and atom is _very_ unresponsive for a minute or two until the message goes away. It's happening everytime I open Atom even if it's the same project.

**Comment by stdavis** [comment]
Would it be helpful for me to open a new issue?

**Comment by lingz90** [comment]
same issue here, and also the result is that a popup says sth like 'autocomplete-paths will not work on this project....'
seems the extention is checking all the files in the project include node_modules path cause there are too many files in the folder and it could not ignore it
