### ISSUE TITLE
File Count without Hiding Node_Modules

### ISSUE THREAD

**Issue by bfletcherbiggs** [atom-community/autocomplete-paths#167]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Attempting to leave my node_modules folder non-excluded while also getting the autocomplete functionality.

### Steps to Reproduce

1. Install Autocomplete without Exclude VCS paths checked
2. Restart Atom 
3. Error as mentioned previously 

**Expected behavior:** I'd like to be able to change the config of autocomplete-paths itself to ignore node_modules even if I have it showing as I occasionally need to reference some of my dependency libraries.

**Actual behavior:** Error as mentioned in [Issue 164](https://github.com/atom-community/autocomplete-paths/issues/164)

**Reproduces how often:** 100%

### Versions

2.11 - autocomplete
1.20.1 - atom

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

I assume I'm just not knowledgeable enough concerning the config to ignore node_modules folder.

**Comment by AburronKing** [comment]
Installed autocomplete-path,but can't ignore the node_modules @_@!

**Comment by aminya** [comment]
You can add `node_modules` to the "ignoredPatterns" list:
```
**/node_modules/**
```
