### ISSUE TITLE
the ignoredPatterns option is not work

### ISSUE THREAD

**Issue by youngjuning** [atom-community/autocomplete-paths#178]
Please help me

**Comment by saschagehlich** [comment]
What did you set the ignorePatterns option to?

**Comment by youngjuning** [comment]
I set it with subdirectory name，like  node_modules

**Comment by youngjuning** [comment]
![2017-10-13_164351](https://user-images.githubusercontent.com/13204332/31537720-bcbf44e8-b035-11e7-9f68-17654eb5c4b9.png)
just like this

**Comment by saschagehlich** [comment]
And what exactly does not work?

**Comment by youngjuning** [comment]
![12](https://user-images.githubusercontent.com/13204332/31537977-916a9684-b036-11e7-838d-47a12bd440c0.png)

I set all subdirectories to this option,but still got warning:

**Comment by youngjuning** [comment]
Maybe, I misunderstand the function of this option.

**Comment by saschagehlich** [comment]
@avaly Apparently `_isPathIgnored` takes the full, absolute path as the argument which makes pattern matching pretty hard. What kind of pattern should users enter here? `*foo*` would ignore *all* paths if the OS user's name was `foobarbaz`

**Comment by youngjuning** [comment]
the absolute path is the correct configuration,But as you say,There is no pattern matching on this option
![170352](https://user-images.githubusercontent.com/13204332/31538735-109a0726-b039-11e7-899b-8cdfd8e92f5e.png)

**Comment by youngjuning** [comment]
Hope you use relative path on this option.thanks
