### ISSUE TITLE
Rebuilding paths cache...  never finishes on large projects

### ISSUE THREAD

**Issue by wyqydsyq** [atom-community/autocomplete-paths#204]
### Description

I see `Rebuilding paths cache... 0 files` in the status bar, `autocomplete-paths` never provides it's functionality of path autocompletion

### Steps to Reproduce

1. Install the plugin
2. Open a large project
3. Notice that `Rebuilding paths cache... 0 files` never completes (or seems to even make progress) and path autocompletion does not work

**Expected behavior:**
Rebuilding the paths cache finishes and path autocompletion works

**Actual behavior:**
Rebuilding the paths cache never finishes and path autocompletion does not work

**Reproduces how often:**
Always

### Versions
Any additional information, configuration or data that might be necessary to reproduce the issue.
Atom: `1.24.0`
autocomplete-paths: `2.12.2`

**Comment by photonauta35** [comment]
the same here. using operating system Debian 9.

**Comment by sagarpanchal** [comment]
Same on Ubuntu 16.04

**Comment by wzdlc1996** [comment]
Same on Manjaro, but when I downgrade to 2.11.0 it works.

**Comment by wyqydsyq** [comment]
Going by the comments it appears we're all using various Linux distributions (I'm on OpenSUSE Tumbleweed), so I'm guessing this issue is Linux-specific

**Comment by beckrao1984** [comment]
same on win10, anybody know how to fix this issue, many thanks

**Comment by francoism90** [comment]
Is this package still in development? Because I'm having the same issue and it seems no fix has been released.

Thanks.

**Comment by kpatrickos** [comment]
Just had to disable the autocomplete-paths package for Atom to work normally

**Comment by PointedEars** [comment]
> Just had to disable the autocomplete-paths package for Atom to work normally

Thanks. The message constantly being there ate all my status bar real estate, too (and I run UHD resolution). After disabling the package, I can finally see “col:line” again.

**Comment by kpatrickos** [comment]
I think autocomplete-paths team should consider implementing _**silent file builder**_ to allow for Atom and the package to fire up immediately and rebuild all paths slowly in the background.

**Comment by aminya** [comment]
Could you add the repository that this happens along with your operating system information?

**Comment by bassamanator** [comment]
I'm having this issue currently. Been working on this project for about 2 months now issue free. Then yesterday after a commit, when I switched back to the main branch, the code in atom didn't change. So I did ```git checkout .``` and that didn't help. So I restarted atom and now I'm stuck 'Rebuilding paths cache...' and the status indicator dot that is usually green is now pulsating yellow. Atom keeps asking me to force close or keep waiting. I disabled autocomplete-paths as per someone's suggestion but that changed nothing except it no longer says 'Rebuilding paths cache...' in the status indicator. Atom is working just fine with other projects.

```
Atom: 1.54.0 x64
Operating System: Manjaro Linux
KDE Plasma Version: 5.20.5
KDE Frameworks Version: 5.78.0
Qt Version: 5.15.2
Kernel Version: 5.10.7-3-MANJARO
OS Type: 64-bit
Processors: 16 × AMD Ryzen 7 2700X Eight-Core Processor
Memory: 31.4 GiB of RAM
Graphics Processor: Radeon RX 580 Series
```

**Comment by bassamanator** [comment]
I discovered something bizarre so I thought I should post it. When I rename the project folder to anything else, atom has no issue loading the project. The actual project folder is **/home/bassam/fractal-task/fractal-task-v2/**. When I rename it to **/home/bassam/fractal-task/fractal-task-v2--/** I see the Rebuilding message for a flash and the project loads fine.

UPDATE: I thought I would test out another folder name just to be safe. The renaming trick is no longer working. I'm now (this is new) getting a maximum file count error:
![image](https://user-images.githubusercontent.com/61985779/107224300-3dc9e180-69e5-11eb-86e0-e31a01a6dd19.png)

**Comment by aminya** [comment]
@bassamanator does running `application: clear project history` solve the issue?

Your case is a rare case. I think the file that stores the project history has become corrupted for some reason.

**Comment by bassamanator** [comment]
@aminya Yes! Running the command worked. I didn't have to delete the cache folders.

Thanks!

**Comment by bassamanator** [comment]
> @bassamanator does running `application: clear project history` solve the issue?
> 
> Your case is a rare case. I think the file that stores the project history has become corrupted for some reason.
> 
> warning the following removes the cache completely (if the above command does not fix it):
> 
> If you really want to clean all the Atom cache you should remove these folders:
> Windows
> 
> ```
> C:\Users\yourname\.atom\.node-gyp
> C:\Users\yourname\.atom\storage
> C:\Users\yourname\.atom\.apm
> C:\Users\yourname\.atom\.npm
> C:\Users\yourname\.atom\compile-cache
> C:\Users\yourname\.atom\snapshot-cache
> C:\Users\yourname\.atom\atom-shell
> C:\Users\yourname\.atom\electron
> C:\Users\yourname\AppData\Local\Temp\atom-build
> C:\Users\yourname\AppData\Local\Temp\atom-cached-atom-shells
> ```
> 
> Linux:
> 
> ```
> ~/.atom/.node-gyp
> ~/.atom/storage
> ~/.atom/.apm
> ~/.atom/.npm
> ~/.atom/compile-cache
> ~/.atom/snapshot-cache
> ~/.atom/atom-shell
> ~/.atom/electron
> ```

Strangely enough this issue has cropped up again. 

1. I did `application: clear project history`.
2. Close atom.
3. I deleted the folders mentioned above.
4. Restarted atom and got stuck on 'Rebuilding paths cache' again.

I added a hyphen to the folder name and atom starts working properly again (`/home/bassam/lip-reading-study/ --> /home/bassam/lip-reading-study-/`).

>Operating System: Manjaro Linux
KDE Plasma Version: 5.22.4
KDE Frameworks Version: 5.85.0
Qt Version: 5.15.2
Kernel Version: 5.11.4-1-rt11-MANJARO (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 2700X Eight-Core Processor
Memory: 31.4 GiB of RAM
Graphics Processor: Radeon RX 580 Series
![image](https://user-images.githubusercontent.com/61985779/130509501-6b72a35c-86c4-49b7-8d3e-4ee2dafd3c35.png)
