### ISSUE TITLE
Atom Becomes Unresponsive / Extremely Slow when Rebuilding path cache is in progress

### ISSUE THREAD

**Issue by kishore-vk** [atom-community/autocomplete-paths#205]
### Description

In Windows, every time Atom is opened, Rebuild path occurs and it tales almost a minute to complete it.

During this time, Atom becomes responsible / extremely slow

### Steps to Reproduce
1. Open Atom with few projects 

**Expected behavior:**  Atom to function normally while path cache happens

**Actual behavior:** Slows down or becomes unresponsive 

**Reproduces how often:** 100%

### Versions

1. Platform: Windows 10
2. Atom Version: Version 1.25
3. Autocomplete path: Version 2.12.2

**Comment by wadehammes** [comment]
This is happening for me too on latest MacOS version.

**Comment by paul8klee** [comment]
same as @cmoses8626 for me.
