### ISSUE TITLE
Exclude ignored files by git

### ISSUE THREAD

**Issue by PierreMarchand20** [atom-community/autocomplete-paths#206]
I know that I can use the option "Exclude VCS Ignored Paths", but it is a global option and I am not sure how it can affect other packages. 

Would it be possible to add this option locally in the package ? (Like we have the option to ignore submodule)

**Comment by booch** [comment]
According to https://github.com/atom-community/autocomplete-paths/wiki/Troubleshooting#maximum-file-limit-exceeded, it *does* exclude files in the `.gitignore` file, but only in the top level of the project. My top-level project almost always consists of a directory full of git-backed repos. It would be nice to support that use case as well. For now, I'm going to have to disable to plugin.

**Comment by aminya** [comment]
You should always enable "Exclude VCS Ignored Paths". This is a unified setting for all the packages to use.
