### ISSUE TITLE
It does not work with *.vue

### ISSUE THREAD

**Issue by dasisyouyu** [atom-community/autocomplete-paths#208]
### Description
autocomplete of *.vue  doesn't seem to work.
What could be the cause?

I browsed # 128 and # 142

<img width="730" alt="2018-04-11 23 46 58" src="https://user-images.githubusercontent.com/16145243/38624309-bbb62d42-3de2-11e8-9276-9773f1ca9972.png">

### Versions
OS: mac el capitan
OS varsion: 10.11.6
Atom    : 1.25.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.10.1

**Comment by lcw2004** [comment]
Add vue extensions in 'config.cson' can solve this problem.

1. Open menu : "File -> Config -> config.cson"
2. Add vue extensions 
`  "autocomplete-paths":
    extensions: [
      "js"
      "jsx"
      "ts"
      "coffee"
      "vue"
    ]
    ignoredNames: false
    normalizeSlashes: false
`
