### ISSUE TITLE
Since there are too many files in the project, can we just get the file path of the specific directory in the project and not get the others

### ISSUE THREAD

**Issue by linjialiang** [atom-community/autocomplete-paths#221]
Since there are too many files in the project, can we just get the file path of the specific directory in the project and not get the others

**Comment by TristanBrotherton** [comment]
I think this would be a massive improvement. I've played around with Ignored Patterns for days, and i can't get it to respect them. I think a much better UX would be a toggle to only autocomplete files in a specified set of directories (specified using a project relative path).

**Comment by EliasTouil** [comment]
I agree, i'm uninstalling it because i can't get it to ignore node_modules

**Comment by aminya** [comment]
You should add `node_modules` to gitignore.
