### ISSUE TITLE
Is there an analogue of this plugin in VSCode?

### ISSUE THREAD

**Issue by eugenet8k** [atom-community/autocomplete-paths#223]
This is rather a request for a general discussion and not a bug. Is there a port or similar functionality of this amazing plugin for VSCode?

These two
https://marketplace.visualstudio.com/items?itemName=ionutvmi.path-autocomplete
https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense

Seem to be close but they are missing the crucial feature, to search the file name across all project paths. Basically, they want me to know where my file is and begin typing either the absolute or relative path. Gross!!

I want to type a few chars and choose my file in the suggestions like this repo plugin does!

**Comment by bmueller-sykes** [comment]
Yeah, I'm kind of amazed there's not an analogue in VSCode. I need to move from Atom to VSCode, and the fact that there isn't a version of this in VSCode is kiiiilllllliiiiinnnngggggg me.

**Comment by bmueller-sykes** [comment]
So...no, then?

**Comment by aminya** [comment]
I don't understand how this issue is related to Atom and @atom-community. Use Atom if you want this feature.

**Comment by bmueller-sykes** [comment]
Was hoping the maintainers would do a version of this for VSCode. It's an amazing plug-in, and kind of astonishing that some version of this doesn't exist for VSCode. Intellisense (or whatever they call it), does a bunch of similar stuff, but not this.
