### ISSUE TITLE
Typing a URL blocks editor for a minute.

### ISSUE THREAD

**Issue by DiThi** [atom-community/autocomplete-paths#38]
In a file that has autocomplete-paths enabled, type

    a = "https://github.com/hello"

After writing the `h` of `hello`, the editor locks up for a while.

**Comment by joefitzgerald** [comment]
What grammar is selected when you do this?

**Comment by joefitzgerald** [comment]
Using the plain-text grammar, I cannot reproduce.

**Comment by joefitzgerald** [comment]
I also tried in an untitled editor, and a saved editor using the plain-text grammar.

**Comment by DiThi** [comment]
Editing existing HTML, JS and coffee files.

**Comment by joefitzgerald** [comment]
@DiThi was the line you mention a few hundred lines down in the file you were editing?

**Comment by DiThi** [comment]
Lines 22 to 35 of a HTML file but I also reproduced it in a JS file in the first line.
