### ISSUE TITLE
Performance issue on files > 150-200 lines

### ISSUE THREAD

**Issue by tststs** [atom-community/autocomplete-paths#39]
Hey there,

recently had massive performance issues while typing and autocomplete-paths enabled.
Everything works fine after disabling the package.

The problem doesn't occur if i'm inside the first 100-150 lines.
After line 150-200 i'm getting a huge performance issue while typing.
While typing it stuck for a few hundred ms every few characters.

Only tested js-files.

Greetings from Berlin
tststs

**Comment by stffndtz** [comment]
+1, had the same issue in CSS-Files

**Comment by doggan** [comment]
:+1:

Same problem immediately after upgrading to 1.0.0.

**Comment by joefitzgerald** [comment]
Does anyone have an example file that they can share (perhaps via a gist) that doesn't have any sensitive information? I'd like to include that file in the repo and reproduce this with a test.

**Comment by joefitzgerald** [comment]
This looks related to #38...

**Comment by doggan** [comment]
Here's a dummy file filled with JSON you can use to reproduce:
https://gist.github.com/doggan/11feabb4d004332f1aab

Start typing at the bottom of the file (i.e. `console.log('hello world');`) with autocomplete-paths enabled and you will see a noticeable delay. Disable the package and the delay disappears.

**Comment by joefitzgerald** [comment]
It doesn't seem to be related to line count - I created a 1000 line file with 1 char on each line, then started typing on line 1001: `a = https://github.com/hello`. Will try with your file @doggan.

**Comment by joefitzgerald** [comment]
Thanks, that file was helpful.

![screen shot 2015-01-29 at 9 25 43 am](https://cloud.githubusercontent.com/assets/744740/5961292/de621c18-a798-11e4-9703-042e1ce49299.png)

**Comment by joefitzgerald** [comment]
This is weird - the size of the file really shouldn't be impacting the time taken to get through this section of code. If anything, the number of files and directories in your current directory should.

This provider should switch to being async in any case.

**Comment by joefitzgerald** [comment]
OK, this seems to occur when there is NOT a `./` or `/` in front of the path on OS X. I.e. just typing "https" at the bottom of that json file reproduces it.

**Comment by joefitzgerald** [comment]
Question: should relative paths that aren't prefixed with `./` (on OS X / Linux) or `.\` (on Windows) be shown? if not, this is an easy fix.

**Comment by doggan** [comment]
I'd say 'no'.

Seems like it would cause a lot of interference with standard autocomplete.

**Comment by joefitzgerald** [comment]
The regex has to change. It's currently: `/[a-zA-Z0-9\.\/_-]*\/[a-zA-Z0-9\.\/_-]*/g` which isn't the best.

**Comment by joefitzgerald** [comment]
The regex is doing a global match and there are no line modifiers. https://github.com/atom/atom/blob/98a874808ea00758d84bb45e0b716498d4916b5b/src/cursor.coffee#L504 dictates the start of the range to search being the last non-blank-row, which in your json = the whole document. That's badness, but not causing the issue. The issue is that the prefix could be the entire document in this scenario, which then causes path.basename / path.dirname to take an eternity.

Thanks for reporting this and figuring it out; it gives me a solid lead to create a test and then fix the issue and prevent future regression.

**Comment by joefitzgerald** [comment]
The old code that identified the prefix constrained the search to a single line:

```coffeescript
prefixOfSelection: (selection) ->
     selectionRange = selection.getBufferRange()
     lineRange = [[selectionRange.start.row, 0], [selectionRange.end.row, @editor.lineTextForBufferRow(selectionRange.end.row).length]]
     prefix = ""
     @editor.getBuffer().scanInRange @wordRegex, lineRange, ({match, range, stop}) ->
       stop() if range.start.isGreaterThan(selectionRange.end)
```

**Comment by doggan** [comment]
Thanks for the fix @joefitzgerald! Performance issues seem to be gone. :sparkles:
