### ISSUE TITLE
Make File Extension Optional

### ISSUE THREAD

**Issue by imperez** [atom-community/autocomplete-paths#40]
There are times when I'm working in Node or LESS/SASS that I'd love for autocomplete paths to not include the file extension. Any chance for a checkbox in the setting that turns this on or off?

**Comment by joefitzgerald** [comment]
This seems reasonable - feel like making a PR?

**Comment by imperez** [comment]
Sure I just created one. Let me know if need me to edit anything else or make any tweakes.

**Comment by joefitzgerald** [comment]
Closing in deference to #44.
