### ISSUE TITLE
atom.service is deprecated

### ISSUE THREAD

**Issue by ghyde** [atom-community/autocomplete-paths#41]
atom.services is no longer available. To register service providers and
consumers, use the `providedServices` and `consumedServices` fields in
your package's package.json.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:64:11)
Object.activate (/Users/user/.atom/packages/autocomplete-paths/lib/autocomplete-paths.coffee:8:25)
```

**Comment by joefitzgerald** [comment]
Yes, we're aware of this - see https://github.com/atom/atom#5277

(By the way, you don't need to open an issue in every repo you get this deprecation warning for)...

**Comment by ghyde** [comment]
Oops, my bad. I didn't realize that the packages were all maintained by the Atom community. Sorry about that.
