### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by hammackj** [atom-community/autocomplete-paths#47]
atom.services is no longer available. To register service providers and
consumers, use the `providedServices` and `consumedServices` fields in
your package's package.json.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:64:11)
Object.activate (/Users/hammackj/.atom/packages/autocomplete-paths/lib/autocomplete-paths.coffee:8:25)
```

**Comment by joefitzgerald** [comment]
This is already fixed. Update atom / your packages and restart atom.
