### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by k3rn31** [atom-community/autocomplete-paths#48]
atom.services is no longer available. To register service providers and
consumers, use the `providedServices` and `consumedServices` fields in
your package's package.json.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:64:11)
Object.activate (/Users/davide/.atom/packages/autocomplete-paths/lib/autocomplete-paths.coffee:8:25)
```

**Comment by joefitzgerald** [comment]
Thus is already fixed. Update your oackages and restart atom.
