### ISSUE TITLE
Customize path separator

### ISSUE THREAD

**Issue by AsaAyers** [atom-community/autocomplete-paths#49]
https://github.com/atom-community/autocomplete-paths/blob/master/lib/paths-provider.coffee#L92

I'm currently stuck using Windows, but I'm writing code that runs through browserify, so even though window's `path.sep` is `\` I need all of mine to be `/`. Every time I autocomplete a directory it escapes my quote and I have to remove and replace the trailing / before I can continue.

I linked to the line that I'm fairly sure controls this, but I'm not sure how it should be customized by the user. A global setting for atom? Is there a concept of per-project settings?

**Comment by AsaAyers** [comment]
I just hard-coded mine locally and it fixes it. Maybe it should switch based on grammar? ¯\\_(ツ)_/¯
 I don't know what different languages should use.

**Comment by rossross** [comment]
Same issue here, anything happening with it?

**Comment by capaj** [comment]
I can't think of a language, where I would prefer '\' instead of '/'. Couldn't we have '/' always?

**Comment by AsaAyers** [comment]
>This is actually a good thing in most cases since the path separator you use is going to depend upon language or framework rather than the computer you're currently using.

#51 looks like a great solution to me

**Comment by kankaristo** [comment]
A customizable separator would be nice, because Lua uses `.` as a separator for require statements. This way, submodules are "automatically" found in subdirectories:
```
require 'mymodule.mysubmodule'
```

This would require the ability to have multiple separators, because almost everything else expects `/` as the separator.

**Comment by danielo515** [comment]
:+1: 
It is really annoying to have to type manually the separator!

**Comment by saschagehlich** [comment]
Discussion moved to #112
