### ISSUE TITLE
Add project root to the completion of absolute paths

### ISSUE THREAD

**Issue by caillou** [atom-community/autocomplete-paths#52]
Say you have the the following project open:

```
Project
|- lib
| |- a.scss
|
|- public
   |- main.scss
```

It would be nice to have `"/li` be autocompleted to `"/lib/"`.

**Comment by joefitzgerald** [comment]
... But that's not a valid path. ./lib/ will be be presented if you type ./li . Is that not sufficient?

**Comment by caillou** [comment]
Depending on the project setup you have, you might need to use absolute paths starting from the root.

If you think this could be made an option, I'd be more than willing to try and send a PR. WDYT?

**Comment by edele** [comment]
@joefitzgerald @caillou that would be cool feature to have

**Comment by alexbet** [comment]
It would be great if you can specify the starting path for the absolute paths in the project like in AutoFileName on SublimeText:
https://github.com/BoundInCode/AutoFileName

That way you can set any path for the absolute path, for example, the 'public' folder in the above example.

**Comment by amraei** [comment]
I also need this feature to get paths relative to the project root. Better approach is the ability to define a root folder for PHP and HTML files separately. 

Current functionality is useless in HTML files, cause we have to start paths from hard disk root folder "/".

**Comment by saschagehlich** [comment]
2.0.0 fixes this / provides a much better autocompletion experience

**Comment by markusmayerroth** [comment]
Sorry, if this is the wrong place to ask – I’m new to github.

I can’t get autocomplete-paths to generate root relative paths like

_/images/image.png_

Isn’t that what @amraei asked and what is part of 2.0.0 according to @saschagehlich?

Setting Relative to true or false has no effect.
I’m on Atom 1.27.1 and autocomplete-paths 2.12.2

Thanks!
