### ISSUE TITLE
C-style comment launches autocomplete-paths

### ISSUE THREAD

**Issue by kankaristo** [atom-community/autocomplete-paths#55]
Writing a C-style comment (either `//` or `/* */`) opens `autocomplete-paths`.

This is especially annoying when ending a multiline comment with `*/`, pressing enter (for a line change) and having it turn into `*/bin/`.

It would be a lot more user-friendly if it didn't launch on `//` or `*/`. The former also happens to be in `http://`, so this would fix that too.

**Comment by joefitzgerald** [comment]
This makes sense.

**Comment by vslinko** [comment]
Do you have any plans on this issue?

I'm suggesting this algorithm:
```
if symbol === "/" and previousSymbol === "/"
  closePreviouslyOpenedPanel()
else if symbol === "*" and previousSymbol === "/"
  closePreviouslyOpenedPanel()
else if symbol === "/" and previousSymbol === "*"
  continue // don't open panel at all
else if symbol === "/"
  openPanel() 
```

**Comment by saschagehlich** [comment]
2.0.0 fixes this
