### ISSUE TITLE
"\" instead of "/"

### ISSUE THREAD

**Issue by piotrrekkk** [atom-community/autocomplete-paths#57]
Hi,
my issue is about separator, on each directory instead of "/" I got "\" and in this case next directory or files are not recognized.
Windows 7, the newest version of Atom and plugin.

**Comment by kangw3n** [comment]
Please refer 
https://github.com/atom-community/autocomplete-paths/pull/51

**Comment by jordanbtucker** [comment]
Please see #79 for a workaround.

**Comment by saschagehlich** [comment]
Discussion has been moved to #112
