### ISSUE TITLE
Not working with autocomplete-php

### ISSUE THREAD

**Issue by Vocal** [atom-community/autocomplete-paths#58]
Hi.
When i type  "/" then not show anything when autocomplete-php is enable.
if  i disable autocomplete-php then it everything good
Please fix it.
Thanks.

i using 
Atom (0.210.0)
autocomplete-paths (1.0.2)
autocomplete-php (0.3.6)
on Ubuntu 15.04

**Comment by saschagehlich** [comment]
2.0.0 should work with PHP
