### ISSUE TITLE
Not work on <script src=""> tag 

### ISSUE THREAD

**Issue by GeoSaboti** [atom-community/autocomplete-paths#60]
Hi, this plugin not work in the `<script src="">` tag.

I'm using Atom 1.0.0

Thanks.

**Comment by lidia-freitas** [comment]
the same here, on linux

**Comment by PhiLhoSoft** [comment]
Works for me. Atom 1.3.1, Win 7.
But it uses \ separators instead of /. Reported in #57.

**Comment by SarjuHansaliya** [comment]
Not working for me in linux, specifically in script tag.
Issue is , it is showing recommendation  but when I try to select with `Enter` or `tab` it is not selecting.
**But**
Link , img tags are working fine.

**Comment by MB116** [comment]
Anybody knows how to fix that bug?

**Comment by saschagehlich** [comment]
Version 2.0.0 works totally differently and should not trigger in this case at all. If you'd like it to trigger when typing `src="`, you can add a custom scope.
