### ISSUE TITLE
Autocomplete+'s "Minimum Word Length" setting not respected

### ISSUE THREAD

**Issue by int3h** [atom-community/autocomplete-paths#63]
Autocomplete-Paths doesn't seem to heed the "Minimum Word Length" setting in Autocomplete+.
### Steps to reproduce:
1. In your Autocomplete+ settings, set "Minimum Word Length" to `3`
2. Go to a source file and type `/`
### Expected Behavior

The Autocomplete+ suggestions list does not appear until I have typed at least 3 characters (for example, `/Us`)
### Observed Behavior

The Autocomplete+ suggestions list appears after typing just 1 character, the `/`, and is populated exclusively with Autocomplete-Paths suggestions.
### Additional Details

Disabling the Autocomplete-Paths package fixes this behavior, making it so typing just a `/` does not trigger the Autocomplete+ suggestions list to appear. Additionally, with Autocomplete-Paths enabled, all other cases but path completion properly wait for 3 characters before triggering the Autocomplete+ suggestions list to appear; only a path complete causes the premature trigger.
### System Info
- Atom: v1.0.5
- Autocomplete-Paths: v1.0.2
- Autocomplete-Plus: v2.19.0
- OS: Mac OS X 10.9.5

**Comment by finchd** [comment]
Can Reproduce. Typing a single character on a blank line causes suggestions exclusively from Autocomplete-Paths, which is ignoring the "Minimum Word Length".

Atom: v1.0.7
Autocomplete-Paths: v1.0.2
Autocomplete-plus: v2.19.0
OS: Debian 9 'Stretch'

**Comment by wassname** [comment]
This is particularly bad when indenting anything with tab, even a new line. Because it will instead select the first path autocomplete.

**Comment by KangarooCreativeTeam** [comment]
> This is particularly evident when working with a list e.g. '-'

Confirmed - I've been hit by this HARD :(

Had to disable this package :(


BOiNG BOiNG
-- HEAD KANGAROO
[KangarooCreativeTeam.com](http://kangaroocreativeteam.com)

**Comment by saschagehlich** [comment]
This should be less painful now that autocomplete-paths is triggered only when needed (e.g. when writing `require "`)
