### ISSUE TITLE
Path Blacklist

### ISSUE THREAD

**Issue by gibsjose** [atom-community/autocomplete-paths#65]
## Feature request: File/Path Blacklist

I would like to request a setting where you can create a list of files/paths to ignore when making suggestions.

It gets very annoying when trying to type comments, add newlines, add tabs, etc. on OS X when `.DS_Store` and other hidden files/unwanted files are constantly popping up in the autocomplete dialogue:

![image](http://g.recordit.co/9PS5kOto91.gif)

The setting could take a list of paths to ignore:

```
.*, *~, ...
```

**Comment by ProLoser** [comment]
Or you could use gitignore

**Comment by gibsjose** [comment]
True, although I can imagine scenarios where you may want files under version control but still never want them popping up in the autocomplete dialogue.

**Comment by cyonder** [comment]
+1

**Comment by francisngo** [comment]
+1 ....very annoying

**Comment by saschagehlich** [comment]
This should be fixed with 2.0.0 as it works completely different
