### ISSUE TITLE
Autocomplete is completing comments?

### ISSUE THREAD

**Issue by optikalefx** [atom-community/autocomplete-paths#67]
when typing // it's trying to find a path. This is not desired behavior
http://cl.ly/image/323W092T1X1Y

**Comment by optikalefx** [comment]
bump?

**Comment by ProLoser** [comment]
Woops just filed a duplicate in #70

**Comment by Iambecomeroot** [comment]
Bump. Also happens for `/**/`.

**Comment by saschagehlich** [comment]
Fixed in 2.0.0
