### ISSUE TITLE
feature request: directory nav

### ISSUE THREAD

**Issue by geddski** [atom-community/autocomplete-paths#68]
Holy smokes I love this plugin. One thing that would make it even would be the ability to hit the right arrow when on a directory and have it expand that directory to show its files/directories just like Finder on OSX:

![image](https://cloud.githubusercontent.com/assets/515722/9402789/e8ee6a42-479d-11e5-92d4-79acf759d95b.png)

Hitting left arrow could go back also like Finder.

I'd seriously **love** this.

**Comment by saschagehlich** [comment]
Sorry, but this is not possible
