### ISSUE TITLE
Add support for aliases

### ISSUE THREAD

**Issue by kayone** [atom-community/autocomplete-paths#69]
so currently in our project we use relative paths, but using an alias, so our require looks like this, 

```
define(
  [
    'projectName/base/utils/browser',
    'projectName/base/models/appModel'
  ],

```

where `project name` is `/git/src/projectName` but right now this doesn't trigger the auto complete, it would be great if we could define aliases to make it work.

**Comment by Dzeks** [comment]
+1

**Comment by saschagehlich** [comment]
Might be working with 2.0.0, but will verify later

**Comment by saschagehlich** [comment]
Doesn't work with 2.0.0, will investigate for a later version

**Comment by saschagehlich** [comment]
Version 2.1.0 now properly resolves symlinks
