### ISSUE TITLE
Adding spaces should cancel autocompletion:

### ISSUE THREAD

**Issue by ProLoser** [atom-community/autocomplete-paths#70]
It sometimes accidentally autocompletes when I'm writing comments. Kind of annoying.

![s0q6iio9pd](https://cloud.githubusercontent.com/assets/67395/9914568/50e12f80-5c67-11e5-9e06-e4ec7dd5cd09.gif)

**Comment by awebdeveloper** [comment]
very annoying. needs to be fixed soon

**Comment by gdaolewe** [comment]
If you go to your autocomplete-plus package settings, you can enter `.comment` under `Scope Blacklist`. This will prevent autocompleting in general while typing in comments.

The one annoying behavior that remains after enabling this is that when you type the first `/` to begin opening a comment, autocomplete-paths starts autocompleting a path (which seems reasonable to me), and then typing a second `/` or '*' to actually open the comment does not hide the results that were already suggested for the first `/`. 

This seems more like an issue for autocomplete-plus to me, that package should hide (or have an option to hide) suggestions when the cursor scope changes to become a blacklisted one.

**Comment by jinjiren** [comment]
I also find it very annoying, so currently there is no solution for this?

**Comment by saschagehlich** [comment]
With 2.0.0 and the new autocomplete-plus API this should be fixed
