### ISSUE TITLE
Autocomplete hangs when editing markdown file

### ISSUE THREAD

**Issue by Hurtak** [atom-community/autocomplete-paths#71]
see https://github.com/atom/autocomplete-plus/issues/627

**Comment by rugk** [comment]
:+1: 

Also experienced this issue. As this is really annoying it should really be fixed in the next time.

I've uploaded a JSON file of the timeline created with the Chromium dev tools, here: https://gist.github.com/rugk/d672a1c1f364a175caa2

**Comment by rugk** [comment]
BTW this issue seems to be a duplicate of https://github.com/atom-community/autocomplete-paths/issues/45.

**Comment by crazy4groovy** [comment]
+1

**Comment by saschagehlich** [comment]
Please check out 2.0.0
