### ISSUE TITLE
Backslash in paths

### ISSUE THREAD

**Issue by afider** [atom-community/autocomplete-paths#72]
Directories are presented with a backslash:

![example](https://3.downloader.disk.yandex.ru/preview/963def89e2607bd30e1b90e39ae82ce589abd8e08674f67c00821dd208396116/inf/DLBpZ5lu7AIL1THMey5b2eWYP7TcIgvNgWsxlIYEcF_JdMz6lRpmi-G2g8vYQ81t1SvYxzEFxY1OGm1RvQIQKg%3D%3D?uid=0&filename=2016-01-02%2023-24-10%20detail.html%20-%20E%20%20SITES%20FIXENG%20fixeng-html%20-%20Atom.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&size=XXL&crop=0)

Windows 8.1
Atom 1.3.2

**Comment by alannsiqueira** [comment]
[+1] /\

**Comment by agusdiyansyah** [comment]
maybe you can change line 92 on file paths-provider.coffee to result += "/"

**Comment by PawelGIX** [comment]
+1

**Comment by avillalobos-atsistemas** [comment]
+1

**Comment by jsilvermist** [comment]
+1, have to backspace every time I type a file path with this.

**Comment by jordanbtucker** [comment]
Please see #79 for a workaround.

**Comment by phojanecki** [comment]
Is is possible to configure it manually that the directories are provided with slash instead of backslash?

**Comment by MattDiMu** [comment]
Looking for the same as @phojanecki, as I need to develop under windows and the server runs under linux using / as path-separator.

**Comment by Rafi993** [comment]
same issue here . They should have provided this under settings so that user can change if he wants / or \ when needed

**Comment by saschagehlich** [comment]
Discussion moved to #112. Will work on this next (as soon as I did some GH issues brooming)
