### ISSUE TITLE
Paths that contain @

### ISSUE THREAD

**Issue by allochi** [atom-community/autocomplete-paths#73]
Hi,

Thanks for the wonderful package, it's amazing.

There is a problem when I try to get the path of a file using `jspm` when I reach a directory with `@` in the name, for example, the following path would stop auto-complete when I reach the part that includes `@`

```
public/jspm_packages/github/Semantic-Org/Semantic-UI@2.1.8/
```

I can't get files and directories within `Semantic-UI@2.1.8/`

`jspm` uses the `@` to include the version of a library in the path.

**Comment by saschagehlich** [comment]
2.0.0 might fix this, not sure though. Will check on this.

**Comment by saschagehlich** [comment]
Works fine with 2.0.0!
