### ISSUE TITLE
Confirmation hotkey is not working.

### ISSUE THREAD

**Issue by const-int** [atom-community/autocomplete-paths#76]
When I  type path autocomplete popup shows but it is not possible to confirm with my default hotkey.
There is aslo no usual arrow(hotkey) icon near suggestions.
![screenshot](https://cloud.githubusercontent.com/assets/5854245/13052928/6e653a90-d40a-11e5-83b4-5e574c669ece.png)

**Comment by jordanbtucker** [comment]
Please see #78 to see if you have the same issue. Thanks.
