### ISSUE TITLE
Doesn't work in C++ files (.h, .cpp)

### ISSUE THREAD

**Issue by matthieuheitz** [atom-community/autocomplete-paths#77]
For some reason, this package works in files like a CMakeLists.txt, or even in keymap.cson, but doesn't in any C++ files.
Any idea why ?
I don't think this package should be language dependant nor file format dependant.

**Comment by Kamairo** [comment]
I have the same problem and would like to know this too. Maybe clang-autocomplete is overwriting the results for c/c++?

**Comment by NickyVSTaiMokWong09** [comment]
Maybe the other plugin affect each other

**Comment by altundasbatu** [comment]
autocomplete-clang and autocomplete-paths do not work together. Disabling autocomplete-clang is the only way for autocomplete-paths to work.

**Comment by saschagehlich** [comment]
3.0.0 should fix this
