### ISSUE TITLE
Enter/Tab not working for confirmation

### ISSUE THREAD

**Issue by petrchutny** [atom-community/autocomplete-paths#78]
When I select the suggestion that I want, neither Tab or enter works to confirm it – it disappears the suggestions and does the enter's or tab's function instead :(
![autocomplete-paths](https://cloud.githubusercontent.com/assets/1197393/13532664/934cea92-e224-11e5-8d66-4f948c0f171a.gif)

**Comment by jordanbtucker** [comment]
Do you have any other plugins installed?

Open the Key Binding Resolver (<kbd>Ctrl/Cmd</kbd>+<kbd>.</kbd>) and see what else is listening for <kbd>Tab</kbd> and <kbd>Enter</kbd> key presses.

**Comment by petrchutny** [comment]
Thanks a lot for the reply. In the resolver, it shows that Emmet overrides it with it's abbreviation expander. After disabling Emmet it works OK. How do I make these two guys not to collide?

**Comment by jordanbtucker** [comment]
Please see https://github.com/emmetio/emmet-atom/issues/225#issuecomment-82669798
