### ISSUE TITLE
why the "/" is the "\"?

### ISSUE THREAD

**Issue by Mrzzchao** [atom-community/autocomplete-paths#79]
why the "/" is the "\"?

**Comment by jsilvermist** [comment]
I also wanted to know this, not very good experience to have to constantly backspace 5 times every time I try to type a file path.

**Comment by jordanbtucker** [comment]
#51 fixes this by letting you choose which path separator you want to use in real time, but the maintainer hasn't bumped the version number in over a year, so none of the merged PRs have taken effect.

In the meantime, you can do the following. Choose a folder where you want to store a local copy of `autocomplete-paths`, and open a command prompt there. Then run the following commands:

```
apm rm autocomplete-paths
git clone https://github.com/atom-community/autocomplete-paths
cd autocomplete-paths
git reset --hard ed62b05
apm install
apm ln
```

The commands above will uninstall the current version of `autocomplete-paths`, download the latest from GitHub, reset the repo to the point where #51 was merged, install the package's dependencies, and install the local copy of the package.

I can't guarantee that this commit is stable, but you can move to any commit you want with `git reset`. If you want to use the bleeding edge version, either leave the `git reset` command out when you clone it or run `git reset --hard HEAD`.

If the maintainer ever bumps the version number, you can just uninstall your local copy and install the latest version with `apm install autocomplete-paths`.

**Comment by jsilvermist** [comment]
Hmm didn't realize that it was so behind, thanks for the info, hope this gets updated soon to be able to be downloaded through apm, but until then, thanks for the workaround! :+1:

**Comment by gluons** [comment]
From atom/apm#518.

Install directly from this repo also work.

`apm install atom-community/autocomplete-paths`

**Comment by saschagehlich** [comment]
Discussion moved to #112. Will work on this next (as soon as I did some GH issues brooming)
