### ISSUE TITLE
atom freeze while editing latex file

### ISSUE THREAD

**Issue by Ehekatl** [atom-community/autocomplete-paths#84]
It just suddenly happen while I input on specific latex file, for now I can't reproduce it on other latex file(maybe I'm not test enough, I'll update if I find something new), try to disable some package and reload atom but it doesn't help, it just randomly keep freeze for 20s and happens more and more often.

**Reproduction Steps:**
1. Open the latex file
2. Several hours gone, everything works well but suddenly
3. Atom freeze
4. And this happen again and again

**Screenshots and GIFs**

![bug](http://7xicnm.com1.z0.glb.clouddn.com/path.PNG)

**Atom version:** 1.7.2
**OS and version:** Windows 10 x64

**Installed packages:**
- activate-power-mode@0.4.1
- aligner@0.21.0
- atom-beautify@0.29.7
- atom-html-preview@0.1.19
- atom-material-syntax@0.4.6
- atom-material-ui@1.2.10
- autocomplete-clang@0.9.3
- autocomplete-paths@1.0.2
- autocomplete-python@1.7.2
- batman-syntax@1.0.1
- draw-package@0.1.2
- figlet@0.5.3
- file-icons@1.7.7
- fonts@1.2.0
- git-time-machine@1.4.1
- highlight-selected@0.11.2
- language-latex@0.6.1
- language-matlab@0.2.1
- latex@0.32.0
- latexer@0.3.0
- linter@1.11.4
- linter-gcc@0.6.12
- linter-javac@1.8.1
- linter-jshint@2.1.0
- linter-pylint@1.2.0
- markdown-pdf@1.5.0
- markdown-preview-plus@2.4.0
- merge-conflicts@1.4.1
- minimap@4.22.1
- minimap-pigments@0.2.0
- pdf-view@0.50.0
- pigments@0.26.0
- platformio-ide-terminal@2.0.9
- project-manager@2.9.7
- rails-snippets@2.3.2
- remote-sync@4.0.1
- symbols-tree-view@0.12.0
- sync-settings@0.7.2
- typewriter-sounds@0.1.0
- wordcount@2.6.0

**Additional information:**
- Problem can be reproduced in safe mode: No
- Problem started happening recently, didn't happen in an older version of Atom: Yes
- Problem can be reliably reproduced, doesn't happen randomly: No
- Problem happens with all files and projects, not only some files or projects: No

**Comment by saschagehlich** [comment]
Please check out 2.0.0
