### ISSUE TITLE
Use / as the root of the current project?

### ISSUE THREAD

**Issue by felipegrin** [atom-community/autocomplete-paths#89]
Is there any way to use / as the current project folder, instead of the root of my computer?

And if there is no way of doing this, maybe it can it be implemented in the future?

**Comment by Cooperdale** [comment]
There's a fork of this doing that. But it's not enough, unless the /gets deleted after you type the next character.
I think that the autocompletion should always use the current folder as root folder actually. It's the only way this can be useful for me.

**Comment by PierBover** [comment]
I'd say there should be different configurable roots.

For example I have a template file which is compiled at build, so the URLs of images are different when I'm working on it and when it's in it final version. So I don't get autocomplete...

An inefficient solution would be for `autocomplete-paths` to search the whole project with matches of paths. So if I'm writing `<img src="static/...` it will look for all folders matching `static`.

A better solution would be to have an `.autocomplete-paths` file on a project to define where `autocomplete-paths` has to start looking for matching folders.

**Comment by saschagehlich** [comment]
2.0.0 only suggests files that are in the current project.
