### ISSUE TITLE
remove "\" or replace for "/"

### ISSUE THREAD

**Issue by raky291** [atom-community/autocomplete-paths#93]
Would be great to have an option to remove or replace the character "\"

![err1](https://cloud.githubusercontent.com/assets/12045722/17083212/b75626a2-5154-11e6-8c7c-213b6e7d8f59.jpg)

**Comment by Lee-SDU** [comment]
I also got this error. Have you solved it, or do anyone knows how to solve it?

**Comment by nicothin** [comment]
+1

**Comment by nicothin** [comment]
https://github.com/atom-community/autocomplete-paths/issues/79#issuecomment-253995057

**Comment by saschagehlich** [comment]
Discussion moved to #112. Will work on this next (as soon as I did some GH issues brooming)
