### ISSUE TITLE
Editor is not responding

### ISSUE THREAD

**Issue by zhylmzr** [atom-community/autocomplete-paths#95]
When i enter "/", the atom is not responding a long time.
![123](https://cloud.githubusercontent.com/assets/15730824/18099372/ccf9dd96-6f18-11e6-9593-860a361093e2.gif)
Then i disable the package, this has never happened!

**Comment by ice-blaze** [comment]
Having more information would be nice. I have this problem too.

- My OS: windows 10
- Atom version: 1.10.2

**Comment by Aisuko** [comment]
Same problem +1
Platform :  
Windows 10 1607
Atom version 1.12.6
autocomplete-paths version 1.0.2

**Comment by saschagehlich** [comment]
This is fixed with 2.0.0, which only suggests files in the same project.
