### ISSUE TITLE
i want "/" not "\"

### ISSUE THREAD

**Issue by Lee-SDU** [atom-community/autocomplete-paths#96]
This is infrustrating. I've tried every method posted in other issues. Does not work.
Description: Atom installed on windows7. Autocomplete-paths in atom->install

**Comment by XaBerr** [comment]
**+1**
If some one add one feature like:
Chose format:
- "/"
- "\"
- "auto"

**Comment by tjx12345** [comment]
you can overwrite file ,
see:
https://github.com/tjx12345/fixed-atom-autocomplete-paths.git

**Comment by nicothin** [comment]
https://github.com/atom-community/autocomplete-paths/issues/79#issuecomment-253995057

**Comment by guizoxxv** [comment]
On #79 @jordanbtucker said: 
> #51 fixes this by letting you choose which path separator you want to use in real time, but the maintainer hasn't bumped the version number in over a year, so none of the merged PRs have taken effect.

and @gluons:
> Install directly from this repo also work. 
> `apm install atom-community/autocomplete-paths`

I was having trouble using `apm` in Windows and didn't had time to search about it so I tried manually donwloading the [autocomplete-paths package ](https://github.com/atom-community/autocomplete-paths) and replacing the files on `C:\Users\user-name\.atom\packages\autocomplete-paths` with this. Worked for me!

**Comment by saschagehlich** [comment]
Discussion moved to #112. Will work on this next (as soon as I did some GH issues brooming)
