### ISSUE TITLE
[ISSUE] When working with ColdFusion

### ISSUE THREAD

**Issue by clang676** [atom-community/autocomplete-paths#98]
When grabbing a file path, the folders present with a \ after the folder name instead of the correct / when using `<cfinclude template="">`

FOR EXAMPLE: A Folder should present as such `IMAGES/`

**Comment by saschagehlich** [comment]
Version 2.0.0 works totally differently and should not trigger in this case at all. If you'd like it to trigger when typing `template="`, you can add a custom scope.
